# Generated by Django 4.2 on 2023-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10, null=True),
        ),
    ]
