# Generated by Django 4.1 on 2023-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0003_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_racket',
            field=models.CharField(choices=[('Power racket', 'Power Racket'), ('All around racket', 'All Around'), ('Speed racket', 'Speed')], default='Speed racket', max_length=20),
        ),
    ]
