# Generated by Django 4.2 on 2023-04-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badminton', '0004_product_type_racket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_racket',
            field=models.CharField(choices=[('Power racket', 'Power Racket'), ('All around racket', 'All Around'), ('Speed racket', 'Speed')], default='All around racket', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept', models.ImageField(blank=True, null=True, upload_to='reciepts')),
                ('status', models.CharField(choices=[('รอการชำระเงิน', 'Unapproved'), ('ชำระเงินแล้ว', 'Aapproved')], default='รอการชำระเงิน', max_length=100)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badminton.profile')),
            ],
        ),
    ]
