# Generated by Django 4.2 on 2023-04-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0006_order_items_alter_order_reciept_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
